import {
  AlertRule,
  AuditEntry,
  AutomationTemplate,
  Campaign,
  InboxMessage,
  InsightCard,
  ScheduleItem,
  TeamMember,
} from "./types";

export const teamMembers: TeamMember[] = [
  {
    id: "u1",
    name: "Ava Patel",
    email: "ava@socialmetrics.ai",
    role: "Admin",
    permissions: ["View all", "Manage campaigns", "Edit mappings", "Approve content"],
    status: "active",
    lastActive: "2m ago",
    initials: "AP",
  },
  {
    id: "u2",
    name: "Jordan Lee",
    email: "jordan@socialmetrics.ai",
    role: "Content Manager",
    permissions: ["Schedule content", "Reply in inbox", "Manage campaigns"],
    status: "active",
    lastActive: "18m ago",
    initials: "JL",
  },
  {
    id: "u3",
    name: "Nina Flores",
    email: "nina@socialmetrics.ai",
    role: "Analyst",
    permissions: ["View dashboards", "Create insights", "Manage alerts"],
    status: "active",
    lastActive: "1h ago",
    initials: "NF",
  },
  {
    id: "u4",
    name: "Marcus Tan",
    email: "marcus@socialmetrics.ai",
    role: "Content Manager",
    permissions: ["Inbox triage", "Notes", "Approvals"],
    status: "invited",
    lastActive: "Pending invite",
    initials: "MT",
  },
];

export const scheduleItems: ScheduleItem[] = [
  {
    id: "post-1",
    title: "Spring creator spotlight",
    caption: "How creator partnerships drove stronger saves and shares this quarter.",
    hashtags: ["#creatorstrategy", "#socialgrowth"],
    platforms: ["Instagram", "Facebook"],
    status: "scheduled",
    date: "2026-04-17",
    time: "09:30",
    owner: "Jordan Lee",
    approvalOwner: "Ava Patel",
    mediaType: "video",
    mediaUrl:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1200&auto=format&fit=crop",
    campaign: "Spring Revenue Sprint",
  },
  {
    id: "post-2",
    title: "Weekly KPI carousel",
    caption: "A swipe-through on what changed in reach, clicks, and subscriber quality.",
    hashtags: ["#marketingops", "#weeklypulse"],
    platforms: ["Instagram"],
    status: "review",
    date: "2026-04-18",
    time: "14:00",
    owner: "Jordan Lee",
    approvalOwner: "Ava Patel",
    mediaType: "image",
    mediaUrl:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop",
    campaign: "Q2 Pipeline Push",
  },
  {
    id: "post-3",
    title: "Customer win screenshot",
    caption: "A quick proof point from a finance client that cut reporting time by 42%.",
    hashtags: ["#b2bmarketing", "#saas"],
    platforms: ["Facebook"],
    status: "failed",
    date: "2026-04-19",
    time: "11:00",
    owner: "Marcus Tan",
    approvalOwner: "Ava Patel",
    mediaType: "image",
    mediaUrl:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1200&auto=format&fit=crop",
    campaign: "Q2 Pipeline Push",
  },
  {
    id: "post-4",
    title: "Founder note on attribution",
    caption: "A candid take on why attribution gets harder as teams scale across channels.",
    hashtags: ["#attribution", "#growthops"],
    platforms: ["Instagram", "Facebook"],
    status: "draft",
    date: "2026-04-20",
    time: "16:15",
    owner: "Ava Patel",
    approvalOwner: "Nina Flores",
    mediaType: "video",
    mediaUrl:
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1200&auto=format&fit=crop",
    campaign: "Executive Brand Lift",
  },
  {
    id: "post-5",
    title: "Benchmark breakdown",
    caption: "Compare your post cadence against top B2B teams without losing voice quality.",
    hashtags: ["#contentops", "#socialbenchmark"],
    platforms: ["Instagram"],
    status: "approved",
    date: "2026-04-21",
    time: "08:45",
    owner: "Jordan Lee",
    approvalOwner: "Ava Patel",
    mediaType: "image",
    mediaUrl:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop",
    campaign: "Spring Revenue Sprint",
  },
  {
    id: "post-6",
    title: "New template launch",
    caption: "Packaging reusable workflow templates for fast-moving social teams.",
    hashtags: ["#workflowautomation", "#teamops"],
    platforms: ["Facebook"],
    status: "published",
    date: "2026-04-15",
    time: "10:10",
    owner: "Ava Patel",
    approvalOwner: "Nina Flores",
    mediaType: "image",
    mediaUrl:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1200&auto=format&fit=crop",
    campaign: "Executive Brand Lift",
  },
];

export const inboxMessages: InboxMessage[] = [
  {
    id: "msg-1",
    customer: "Sarah Jenkins",
    handle: "@sjenkins.design",
    platform: "Instagram",
    status: "open",
    priority: "urgent",
    assignedTo: "Marcus Tan",
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop",
    lastSeen: "3m ago",
    tags: ["VIP account", "Upgrade intent"],
    history: [
      { label: "Lifetime replies", value: "14" },
      { label: "Avg engagement", value: "8.2%" },
      { label: "Revenue influenced", value: "$12.4k" },
    ],
    notes: ["Asked for agency pricing last month", "Prefers short answers with screenshots"],
    thread: [
      {
        id: "t1",
        author: "Sarah Jenkins",
        kind: "customer",
        message:
          "We’re pitching your platform internally. Can you send a tighter breakdown of reporting permissions for regional managers?",
        time: "09:12",
      },
      {
        id: "t2",
        author: "Marcus Tan",
        kind: "note",
        message: "Escalate if they ask about SSO. Their last note mentioned Okta.",
        time: "09:14",
      },
    ],
  },
  {
    id: "msg-2",
    customer: "BluePeak Ventures",
    handle: "@bluepeakvc",
    platform: "Facebook",
    status: "pending",
    priority: "high",
    assignedTo: "Jordan Lee",
    avatar:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop",
    lastSeen: "23m ago",
    tags: ["Campaign feedback"],
    history: [
      { label: "Open threads", value: "2" },
      { label: "Response SLA", value: "18m" },
      { label: "Follower tier", value: "Enterprise" },
    ],
    notes: ["Waiting for campaign owner confirmation"],
    thread: [
      {
        id: "t3",
        author: "BluePeak Ventures",
        kind: "customer",
        message:
          "The launch creative looks strong, but can you confirm whether the boosted version keeps the same UTM parameters?",
        time: "08:41",
      },
    ],
  },
  {
    id: "msg-3",
    customer: "Marcus Chen",
    handle: "@mchen.media",
    platform: "Instagram",
    status: "resolved",
    priority: "medium",
    assignedTo: "Ava Patel",
    avatar:
      "https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=200&auto=format&fit=crop",
    lastSeen: "2h ago",
    tags: ["Resolved", "Billing"],
    history: [
      { label: "CSAT", value: "9.4/10" },
      { label: "Retention", value: "14 months" },
      { label: "Last campaign", value: "Creator Sprint" },
    ],
    notes: ["Close loop in weekly recap"],
    thread: [
      {
        id: "t4",
        author: "Marcus Chen",
        kind: "customer",
        message: "Appreciate the quick turnaround. The export issue is fixed on our side now.",
        time: "Yesterday",
      },
      {
        id: "t5",
        author: "Ava Patel",
        kind: "agent",
        message: "Perfect. We’ve kept the incident tagged in case you need a recovery export later.",
        time: "Yesterday",
      },
    ],
  },
];

export const insights: InsightCard[] = [
  {
    id: "ins-1",
    title: "Instagram engagement increased by 35%",
    summary: "Reels posted before 10 AM generated higher saves and stronger profile visits this week.",
    severity: "positive",
    metric: "Engagement rate",
    delta: "+35%",
    action: "Schedule two more morning reels",
  },
  {
    id: "ins-2",
    title: "Revenue anomaly detected on paid social",
    summary: "Revenue per click dropped after the audience split on the Q2 retargeting campaign.",
    severity: "critical",
    metric: "Revenue per click",
    delta: "-22%",
    action: "Inspect campaign allocation",
  },
  {
    id: "ins-3",
    title: "Top-performing post this month",
    summary: "The creator playbook carousel delivered 2.4x more shares than your median educational post.",
    severity: "neutral",
    metric: "Shares",
    delta: "2.4x",
    action: "Clone format for next week",
  },
  {
    id: "ins-4",
    title: "Traffic dip likely tied to delayed posting",
    summary: "Website sessions were soft on Tuesday after two approved posts missed their scheduled publish windows.",
    severity: "warning",
    metric: "Traffic",
    delta: "-14%",
    action: "Review scheduling queue",
  },
];

export const alertRules: AlertRule[] = [
  {
    id: "rule-1",
    name: "High-value engagement spike",
    metric: "Instagram engagement rate",
    operator: ">",
    threshold: "18%",
    destination: { inApp: true, email: true },
    enabled: true,
  },
  {
    id: "rule-2",
    name: "Revenue drop guardrail",
    metric: "Revenue",
    operator: "drop",
    threshold: "12%",
    destination: { inApp: true, email: false },
    enabled: true,
  },
  {
    id: "rule-3",
    name: "Traffic quality alert",
    metric: "Returning users",
    operator: "<",
    threshold: "1,250",
    destination: { inApp: true, email: true },
    enabled: false,
  },
];

export const campaigns: Campaign[] = [
  {
    id: "camp-1",
    name: "Spring Revenue Sprint",
    objective: "Drive qualified demos from organic content",
    platforms: ["Instagram", "Facebook"],
    budget: 18000,
    spend: 12240,
    status: "active",
    clicks: 14320,
    engagement: 8.4,
    revenue: 46200,
    start: "2026-04-01",
    end: "2026-05-15",
    assets: [
      { id: "a1", title: "Carousel v2", type: "image" },
      { id: "a2", title: "Founder reel cutdown", type: "video" },
    ],
    linkedPosts: ["post-1", "post-5"],
  },
  {
    id: "camp-2",
    name: "Q2 Pipeline Push",
    objective: "Retarget late-stage followers with conversion proof",
    platforms: ["Facebook"],
    budget: 12500,
    spend: 12500,
    status: "completed",
    clicks: 9820,
    engagement: 6.9,
    revenue: 33100,
    start: "2026-03-01",
    end: "2026-04-10",
    assets: [
      { id: "a3", title: "Case study static", type: "image" },
      { id: "a4", title: "Proof quote edit", type: "image" },
    ],
    linkedPosts: ["post-2", "post-3"],
  },
  {
    id: "camp-3",
    name: "Executive Brand Lift",
    objective: "Increase thought-leadership reach for leadership team",
    platforms: ["Instagram", "Facebook"],
    budget: 9800,
    spend: 3040,
    status: "draft",
    clicks: 2180,
    engagement: 9.2,
    revenue: 8400,
    start: "2026-04-20",
    end: "2026-06-01",
    assets: [
      { id: "a5", title: "Portrait cover", type: "image" },
      { id: "a6", title: "Exec reel storyboard", type: "video" },
    ],
    linkedPosts: ["post-4", "post-6"],
  },
];

export const automationTemplates: AutomationTemplate[] = [
  {
    id: "tpl-1",
    name: "Lead Capture Router",
    description: "Assign high-intent comments to sales and notify Slack-equivalent channel.",
    nodes: [
      { id: "n1", kind: "trigger", title: "New comment", subtitle: "Facebook or Instagram", x: 40, y: 90 },
      { id: "n2", kind: "condition", title: "Contains pricing intent", subtitle: "Keywords or AI label", x: 320, y: 80 },
      { id: "n3", kind: "action", title: "Assign to owner", subtitle: "Round-robin sales queue", x: 620, y: 50 },
      { id: "n4", kind: "action", title: "Send notification", subtitle: "Team inbox + email", x: 620, y: 170 },
    ],
  },
  {
    id: "tpl-2",
    name: "Engagement Booster",
    description: "Alert the team when a post outperforms threshold and create a similar-content task.",
    nodes: [
      { id: "n5", kind: "trigger", title: "Post published", subtitle: "Any connected profile", x: 40, y: 90 },
      { id: "n6", kind: "condition", title: "Engagement > 12%", subtitle: "1-hour rolling window", x: 320, y: 80 },
      { id: "n7", kind: "action", title: "Create content task", subtitle: "Add to schedule backlog", x: 620, y: 50 },
      { id: "n8", kind: "action", title: "Notify marketing lead", subtitle: "In-app notification", x: 620, y: 170 },
    ],
  },
  {
    id: "tpl-3",
    name: "Auto-reply Safety Net",
    description: "Reply with a template, add a note, and escalate if the thread stays open.",
    nodes: [
      { id: "n9", kind: "trigger", title: "New direct message", subtitle: "Instagram only", x: 40, y: 90 },
      { id: "n10", kind: "condition", title: "After-hours", subtitle: "Outside support window", x: 320, y: 80 },
      { id: "n11", kind: "action", title: "Send template", subtitle: "Reply in under 30 seconds", x: 620, y: 50 },
      { id: "n12", kind: "action", title: "Escalate next morning", subtitle: "Assign to inbox lead", x: 620, y: 170 },
    ],
  },
];

export const auditLog: AuditEntry[] = [
  {
    id: "audit-1",
    actor: "Ava Patel",
    action: "approved",
    target: "Spring creator spotlight",
    at: "10 minutes ago",
  },
  {
    id: "audit-2",
    actor: "Jordan Lee",
    action: "created",
    target: "Revenue anomaly guardrail",
    at: "42 minutes ago",
  },
  {
    id: "audit-3",
    actor: "Nina Flores",
    action: "exported",
    target: "Campaign performance snapshot",
    at: "Today, 09:12",
  },
  {
    id: "audit-4",
    actor: "Marcus Tan",
    action: "resolved",
    target: "Sarah Jenkins support thread",
    at: "Yesterday",
  },
];
